import { catalogueImagePathFromRef } from "./catalogue-image";
import type { Product } from "./types";

type ProductSeed = {
  ref: string;
  name: string;
  category: "Industriel" | "Agricole";
  resolution: string;
  plage: string;
  maxError: string;
  tags: string[];
  description_fr: string;
};

const SEEDS: ProductSeed[] = [
  {
    ref: "REF-IND-001",
    name: "Micrometre Exterieur Digital 25-50 mm",
    category: "Industriel",
    resolution: "0.001 mm",
    plage: "25 - 50 mm",
    maxError: "+/-0.002 mm",
    tags: ["IP65", "COFRAC"],
    description_fr:
      "Controle dimensionnel haute precision pour atelier mecanique et metrologie de production.",
  },
  {
    ref: "REF-IND-002",
    name: "Pied a Coulisse Digital Inox 150 mm",
    category: "Industriel",
    resolution: "0.01 mm",
    plage: "0 - 150 mm",
    maxError: "+/-0.02 mm",
    tags: ["IP54"],
    description_fr: "Mesure rapide des cotes exterieures et interieures en ligne de production.",
  },
  {
    ref: "REF-IND-003",
    name: "Comparateur Electronique 12.7 mm",
    category: "Industriel",
    resolution: "0.001 mm",
    plage: "0 - 12.7 mm",
    maxError: "+/-0.003 mm",
    tags: ["COFRAC"],
    description_fr: "Controle de battement, faux-rond et concentricite sur postes critiques.",
  },
  {
    ref: "REF-IND-004",
    name: "Indicateur a Levier 0.8 mm",
    category: "Industriel",
    resolution: "0.002 mm",
    plage: "0 - 0.8 mm",
    maxError: "+/-0.004 mm",
    tags: ["IP40"],
    description_fr: "Mesure de faible deplacement pour reglages fins et alignement machine.",
  },
  {
    ref: "REF-IND-005",
    name: "Jauge de Profondeur Digital 300 mm",
    category: "Industriel",
    resolution: "0.01 mm",
    plage: "0 - 300 mm",
    maxError: "+/-0.03 mm",
    tags: ["IP67"],
    description_fr: "Verification de profondeur de perçage et logements techniques.",
  },
  {
    ref: "REF-IND-006",
    name: "Manometre Process 0-400 bar",
    category: "Industriel",
    resolution: "0.1 bar",
    plage: "0 - 400 bar",
    maxError: "Classe 1.0",
    tags: ["ATEX"],
    description_fr: "Surveillance pression sur circuits hydrauliques et pneumatiques.",
  },
  {
    ref: "REF-IND-007",
    name: "Transmetteur Pression 0-16 bar",
    category: "Industriel",
    resolution: "0.01 bar",
    plage: "0 - 16 bar",
    maxError: "+/-0.1% FS",
    tags: ["IP67"],
    description_fr: "Instrumentation process pour supervision et regulation continue.",
  },
  {
    ref: "REF-IND-008",
    name: "Thermometre PT100 Process",
    category: "Industriel",
    resolution: "0.1 C",
    plage: "-50 - 250 C",
    maxError: "+/-0.3 C",
    tags: ["IP65"],
    description_fr: "Mesure temperature process, cuves et circuits thermiques.",
  },
  {
    ref: "REF-IND-009",
    name: "Camera Thermique Industrielle",
    category: "Industriel",
    resolution: "0.1 C",
    plage: "-20 - 650 C",
    maxError: "+/-2 C",
    tags: ["IP54"],
    description_fr: "Diagnostic thermique des armoires, moteurs et points chauds.",
  },
  {
    ref: "REF-IND-010",
    name: "Capteur Couple 0-500 Nm",
    category: "Industriel",
    resolution: "0.1 Nm",
    plage: "0 - 500 Nm",
    maxError: "+/-0.5% FS",
    tags: ["COFRAC"],
    description_fr: "Validation de serrage et controle de couple sur assemblages mecaniques.",
  },
  {
    ref: "REF-IND-011",
    name: "Vibrometre Portable 10-1000 Hz",
    category: "Industriel",
    resolution: "0.01 mm/s",
    plage: "0 - 200 mm/s",
    maxError: "+/-5%",
    tags: ["IP65"],
    description_fr: "Analyse vibratoire preventive pour maintenance conditionnelle.",
  },
  {
    ref: "REF-IND-012",
    name: "Rugosimetre Portable Ra/Rz",
    category: "Industriel",
    resolution: "0.001 um",
    plage: "0.005 - 16 um",
    maxError: "+/-10%",
    tags: ["COFRAC"],
    description_fr: "Controle etat de surface des pieces usinees et rectifiees.",
  },

  {
    ref: "REF-AGR-001",
    name: "Comparateur Analogique Standard 10 mm",
    category: "Agricole",
    resolution: "0.01 mm",
    plage: "0 - 10 mm",
    maxError: "+/-0.015 mm",
    tags: ["COFRAC"],
    description_fr: "Controle d usure de composants mecaniques sur materiel agricole.",
  },
  {
    ref: "REF-AGR-002",
    name: "Mesureur Humidite Sol Capacitif",
    category: "Agricole",
    resolution: "0.1 %",
    plage: "0 - 100 %",
    maxError: "+/-2 %",
    tags: ["IP67"],
    description_fr: "Suivi de l humidite des parcelles pour pilotage irrigation.",
  },
  {
    ref: "REF-AGR-003",
    name: "Debitmetre Irrigation 1-60 m3/h",
    category: "Agricole",
    resolution: "0.1 m3/h",
    plage: "1 - 60 m3/h",
    maxError: "+/-1.5%",
    tags: ["IP68"],
    description_fr: "Mesure de debit sur reseaux d irrigation et distribution eau.",
  },
  {
    ref: "REF-AGR-004",
    name: "Sonde pH Sol Portable",
    category: "Agricole",
    resolution: "0.01 pH",
    plage: "0 - 14 pH",
    maxError: "+/-0.05 pH",
    tags: ["IP65"],
    description_fr: "Evaluation rapide de l acidite des sols en exploitation.",
  },
  {
    ref: "REF-AGR-005",
    name: "Conductivimetre Terrain",
    category: "Agricole",
    resolution: "1 uS/cm",
    plage: "0 - 20000 uS/cm",
    maxError: "+/-2%",
    tags: ["IP67"],
    description_fr: "Controle salinite et conductivite pour fertigation.",
  },
  {
    ref: "REF-AGR-006",
    name: "Refractometre Brix Digital",
    category: "Agricole",
    resolution: "0.1 Brix",
    plage: "0 - 95 Brix",
    maxError: "+/-0.2 Brix",
    tags: ["IP65"],
    description_fr: "Controle teneur en sucre sur fruits, jus et produits transformes.",
  },
  {
    ref: "REF-AGR-007",
    name: "Balance de Precision 30 kg",
    category: "Agricole",
    resolution: "1 g",
    plage: "0 - 30 kg",
    maxError: "+/-2 g",
    tags: ["IP54"],
    description_fr: "Pesage de lots, semences et intrants sur poste mobile.",
  },
  {
    ref: "REF-AGR-008",
    name: "Capteur Temperature/Humidite Serre",
    category: "Agricole",
    resolution: "0.1 C / 0.1 %RH",
    plage: "-20 - 60 C",
    maxError: "+/-0.5 C",
    tags: ["IP65"],
    description_fr: "Pilotage microclimat serre avec remontes stabilisees.",
  },
  {
    ref: "REF-AGR-009",
    name: "Manometre Hydraulique Tracteur 0-250 bar",
    category: "Agricole",
    resolution: "1 bar",
    plage: "0 - 250 bar",
    maxError: "Classe 1.6",
    tags: ["IP54"],
    description_fr: "Controle pression hydraulique sur circuits auxiliaires.",
  },
  {
    ref: "REF-AGR-010",
    name: "Tensiometre Sol 0-100 kPa",
    category: "Agricole",
    resolution: "1 kPa",
    plage: "0 - 100 kPa",
    maxError: "+/-2 kPa",
    tags: ["IP65"],
    description_fr: "Suivi stress hydrique pour decision irrigation de precision.",
  },
  {
    ref: "REF-AGR-011",
    name: "Anemometre Portable 0-30 m/s",
    category: "Agricole",
    resolution: "0.1 m/s",
    plage: "0 - 30 m/s",
    maxError: "+/-3%",
    tags: ["IP67"],
    description_fr: "Verification vent pour pulverisation et interventions exterieures.",
  },
  {
    ref: "REF-AGR-012",
    name: "Station Meteo Agro Connectee",
    category: "Agricole",
    resolution: "0.1 C / 0.1 mm",
    plage: "-40 - 80 C",
    maxError: "+/-0.4 C",
    tags: ["IP66", "COFRAC"],
    description_fr: "Suivi meteo local pour pilotage cultural et maintenance preventive.",
  },
];

const PRODUCT_IMAGE_BY_REF: Record<string, string> = {
  "REF-IND-001": "https://www.manutan.co.uk/img/S/GRP/ST/AIG2544511.jpg",
  "REF-IND-002": "https://www.manutan.fr/img/S/GRP/ST/AIG2543183.jpg",
  "REF-IND-003": "https://www.manutan.fr/img/S/GRP/ST/AIG3011278.jpg",
  "REF-IND-004": "https://www.manutan.fr/img/S/GRP/ST/AIG299633.jpg",
  "REF-IND-005": "https://www.manutan.fr/img/S/GRP/ST/AIG3011276.jpg",
  "REF-IND-006": "https://www.manutan.fr/img/S/GRP/ST/AIG3498163.jpg",
  "REF-IND-007": "https://www.manutan.fr/img/S/GRP/ST/AIG476957.jpg",
  "REF-IND-008": "https://www.manutan.fr/img/S/GRP/ST/AIG46610880.jpg",
  "REF-IND-009": "https://www.manutan.fr/img/S/GRP/ST/AIG55747118.jpg",
  "REF-IND-010": "https://www.manutan.fr/img/S/GRP/ST/AIG5234648.jpg",
  "REF-IND-011": "https://www.manutan.fr/img/S/GRP/ST/AIG5234546.jpg",
  "REF-IND-012": "https://www.manutan.fr/img/S/GRP/ST/AIG5234545.jpg",
  "REF-AGR-001": "https://www.manutan.fr/img/S/GRP/ST/AIG3325198.jpg",
  "REF-AGR-002": "https://www.manutan.fr/img/S/GRP/IC/AIG36419164.jpg",
  "REF-AGR-003": "https://www.manutan.fr/img/S/GRP/ST/AIG6767423.jpg",
  "REF-AGR-004": "https://www.manutan.fr/img/S/GRP/ST/AIG297510.jpg",
  "REF-AGR-005": "https://www.manutan.fr/img/S/GRP/ST/AIG328413.jpg",
  "REF-AGR-006": "https://www.manutan.fr/img/S/GRP/ST/AIG3156106.jpg",
  "REF-AGR-007": "https://www.manutan.fr/img/S/GRP/ST/AIG7419098.jpg",
  "REF-AGR-008": "https://www.manutan.fr/img/S/GRP/IC/AIG8417822.jpg",
  "REF-AGR-009": "https://www.manutan.fr/img/S/GRP/ST/AIG3498158.jpg",
  "REF-AGR-010": "https://www.manutan.fr/img/S/GRP/IC/AIG2547370.jpg",
  "REF-AGR-011": "https://www.manutan.fr/img/S/GRP/IC/AIG298998.jpg",
  "REF-AGR-012": "https://www.manutan.fr/img/S/GRP/IC/AIG58006004.jpg",
};

/** Optional Arabic marketing copy per ref — omit key to fall back to French in UI. */
const PRODUCT_DESCRIPTION_AR: Partial<Record<string, string>> = {
  "REF-IND-001":
    "مراقبة بُعد عالية الدقة لورشة الميكانيك والقياس في الإنتاج.",
  "REF-IND-002": "قياس سريع للأبعاد الخارجية والداخلية على خط الإنتاج.",
  "REF-IND-003": "مراقبة الاهتزاز والدوران والتماثل على المحطات الحساسة.",
  "REF-IND-004": "قياس انحرافات صغيرة لضبط دقيق ومحاذاة الآلات.",
  "REF-IND-005": "التحقق من عمق الثقوب والمقاعد التقنية.",
  "REF-IND-006": "مراقبة الضغط على الدوائر الهيدروليكية والهوائية.",
  "REF-IND-007": "أجهزة قياس للمراقبة والتنظيم المستمر في الصناعة.",
  "REF-IND-008": "قياس حرارة العمليات والخزانات والدوائر الحرارية.",
  "REF-IND-009": "تشخيص حراري للخزانات والمحركات والنقاط الساخنة.",
  "REF-IND-010": "التحقق من عزم الربط والتحكم على المجموعات الميكانيكية.",
  "REF-IND-011": "تحليل اهتزازي وقائي للصيانة الشرطية.",
  "REF-IND-012": "مراقبة خشونة سطح القطع المشغّلة والمشذّبة.",
  "REF-AGR-001": "مراقبة تآكل المكوّنات الميكانيكية على المعدات الفلاحية.",
  "REF-AGR-002": "متابعة رطوبة التربة لتحسين الري.",
  "REF-AGR-003": "قياس التدفق على شبكات الري وتوزيع المياه.",
  "REF-AGR-004": "تقييم سريع لحموضة التربة في المزرعة.",
  "REF-AGR-005": "مراقبة الملوحة والتوصيل الكهربي للتسميد المائي.",
  "REF-AGR-006": "مراقبة نسبة السكر في الفواكه والعصائر والمنتجات.",
  "REF-AGR-007": "وزن الدفعات والبذور والمدخلات على محطة متنقلة.",
  "REF-AGR-008": "ضبط المناخ الدقيق في البيوت المحمية.",
  "REF-AGR-009": "مراقبة الضغط الهيدروليكي للجرارات على الدوائر المساعدة.",
  "REF-AGR-010": "متابعة الإجهاد المائي لقرارات الري الدقيق.",
  "REF-AGR-011": "التحقق من الرياح للرش والتدخلات الخارجية.",
  "REF-AGR-012": "متابعة الطقس المحلي للزراعة والصيانة الوقائية.",
};

export type CatalogLang = "FR" | "AR";

export function getProductDescription(product: Product, lang: CatalogLang): string {
  if (lang === "AR") {
    const ar = product.description_ar?.trim();
    if (ar) return ar;
  }
  return product.description_fr || product.description || "";
}

export const PRODUCTS: Product[] = SEEDS.map((seed, index) => ({
  id: String(index + 1),
  ref: seed.ref,
  name: seed.name,
  category: seed.category,
  image: PRODUCT_IMAGE_BY_REF[seed.ref] ?? catalogueImagePathFromRef(seed.ref),
  resolution: seed.resolution,
  maxError: seed.maxError,
  tags: seed.tags,
  description_fr: seed.description_fr,
  description_ar: PRODUCT_DESCRIPTION_AR[seed.ref],
  description: seed.description_fr,
  plage: seed.plage,
  specifications: {
    "Plage de mesure": seed.plage,
    Resolution: seed.resolution,
    "Erreur maximale": seed.maxError,
    Protection: (seed.tags.find((t) => t.startsWith("IP")) || "N/A"),
  },
}));
